build: Add check for dirty worktree after install-slsactl
Signed-off-by: Paulo Gomes <paulo.gomes@suse.com>

diff --git a/.github/workflows/test-actions.yml b/.github/workflows/test-actions.yml
--- a/.github/workflows/test-actions.yml
+++ b/.github/workflows/test-actions.yml
@@ -29,6 +29,13 @@ jobs:
     - uses: ./actions/install-slsactl
     - run: slsactl version
       shell: bash
+    - name: Check for dirty worktree
+      if: runner.os == 'Linux'
+      run: |
+        if [[ -n $(git status --porcelain) ]]; then
+          echo "ERROR: The install-slsactl action left the worktree dirty"
+          exit 1
+        fi
 
   test-verify-action:
     strategy:
